-- Generated by nwg-displays on 2026-09-08 at 18:33:12. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@144.0",
    position = "2560x167",
    scale = 1.0,
    vrr = 1
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "2560x1440@144.0",
    position = "0x0",
    scale = 1,
    vrr = 1
})
